import type {Product} from "#/lib/types.ts";

export const SAMPLE_PRODUCTS: Product[] = [
    {
        id: '1',
        name: 'Sustainable Linen Shirt',
        description: 'Crafted from organic linen, perfect for warm weather. Features a relaxed fit and timeless design.',
        price: 89.00,
        compareAtPrice: 129.00,
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
        ],
        category: 'women',
        subcategory: 'tops',
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Natural', 'Sage Green', 'Cloud Grey'],
        material: 'Organic Linen',
        careInstructions: 'Machine wash cold, gentle cycle',
        inStock: true,
        inventory: 45,
        rating: 4.8,
        reviews: 124,
        sku: 'SKU-001',
        createdAt: new Date('2024-01-15'),
    },
    {
        id: '2',
        name: 'Minimalist Wool Blazer',
        description: 'Tailored wool blazer with clean lines. Perfect for professional settings or smart casual.',
        price: 179.00,
        compareAtPrice: 249.00,
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
        ],
        category: 'women',
        subcategory: 'outerwear',
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Charcoal', 'Camel'],
        material: 'Wool Blend',
        careInstructions: 'Dry clean recommended',
        inStock: true,
        inventory: 28,
        rating: 4.9,
        reviews: 89,
        sku: 'SKU-002',
        createdAt: new Date('2024-01-20'),
    },
    {
        id: '3',
        name: 'Organic Cotton Tee',
        description: 'Essential basics made from 100% organic cotton. Comfortable, durable, and eco-friendly.',
        price: 39.00,
        compareAtPrice: 59.00,
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
        ],
        category: 'unisex',
        subcategory: 'basics',
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['White', 'Black', 'Sage Green', 'Cream'],
        material: 'Organic Cotton',
        careInstructions: 'Machine wash warm',
        inStock: false,
        inventory: 120,
        rating: 4,
        reviews: 256,
        sku: 'SKU-003',
        createdAt: new Date('2024-01-25'),
    },
    {
        id: '4',
        name: 'Recycled Denim Jeans',
        description: 'Classic jeans made from 70% recycled denim. Comfort meets sustainability.',
        price: 99.00,
        compareAtPrice: 149.00,
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
        ],
        category: 'unisex',
        subcategory: 'bottoms',
        sizes: ['24', '25', '26', '27', '28', '29', '30', '31', '32'],
        colors: ['Dark Wash', 'Light Wash', 'Black'],
        material: 'Recycled Denim',
        careInstructions: 'Machine wash cold, turn inside out',
        inStock: true,
        inventory: 67,
        rating: 4.6,
        reviews: 178,
        sku: 'SKU-004',
        createdAt: new Date('2024-02-01'),
    },
    {
        id: '5',
        name: 'Linen Trousers',
        description: 'Lightweight linen trousers perfect for summer. Features a high waist and tapered silhouette.',
        price: 119.00,
        image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
        ],
        category: 'women',
        subcategory: 'bottoms',
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Natural', 'Sage Green'],
        material: 'Linen',
        careInstructions: 'Gentle wash, lay flat to dry',
        inStock: true,
        inventory: 34,
        rating: 4.5,
        reviews: 67,
        sku: 'SKU-005',
        createdAt: new Date('2024-02-05'),
    },
    {
        id: '6',
        name: 'Leather Crossbody Bag',
        description: 'Handcrafted from vegetable-tanned leather. A versatile accessory for any occasion.',
        price: 249.00,
        compareAtPrice: 349.00,
        image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=500&fit=crop',
        ],
        category: 'accessories',
        subcategory: 'bags',
        colors: ['Natural Tan', 'Charcoal', 'Cognac'],
        material: 'Vegetable-tanned Leather',
        careInstructions: 'Condition with leather balm regularly',
        inStock: true,
        inventory: 15,
        rating: 4.9,
        reviews: 92,
        sku: 'SKU-006',
        createdAt: new Date('2024-02-10'),
    },
    {
        id: '7',
        name: 'Wool Sweater',
        description: 'Cozy merino wool sweater, breathable and temperature regulating.',
        price: 139.00,
        compareAtPrice: 199.00,
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
        ],
        category: 'unisex',
        subcategory: 'knitwear',
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Cream', 'Charcoal', 'Sage Green'],
        material: 'Merino Wool',
        careInstructions: 'Hand wash or delicate cycle',
        inStock: true,
        inventory: 42,
        rating: 4.8,
        reviews: 134,
        sku: 'SKU-007',
        createdAt: new Date('2024-02-15'),
    },
    {
        id: '8',
        name: 'Hemp Canvas Sneakers',
        description: 'Comfortable and durable sneakers made from sustainable hemp canvas.',
        price: 129.00,
        compareAtPrice: 179.00,
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
        ],
        category: 'unisex',
        subcategory: 'footwear',
        sizes: ['5', '6', '7', '8', '9', '10', '11', '12', '13'],
        colors: ['Natural', 'Charcoal', 'Sage Green'],
        material: 'Hemp Canvas',
        careInstructions: 'Wipe clean with damp cloth',
        inStock: true,
        inventory: 56,
        rating: 4.7,
        reviews: 145,
        sku: 'SKU-008',
        createdAt: new Date('2024-02-20'),
    },
]