import {type Product} from './types'

export const SAMPLE_PRODUCTS: Product[] = [
    {
        id: '1',
        name: 'Silk Satin Blouse',
        description: 'Elegant satin blouse with a relaxed silhouette and timeless design for work or evening wear.',
        price: 89.00,
        compareAtPrice: 129.00,
        image: 'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=500&h=500&fit=crop',
        ],
        category: 'women',
        subcategory: 'tops',
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Ivory', 'Champagne', 'Black'],
        material: 'Silk Satin',
        careInstructions: 'Hand wash cold',
        inStock: true,
        inventory: 45,
        rating: 4.8,
        reviews: 124,
        sku: 'SKU-001',
        createdAt: new Date('2024-01-15'),
    },
    {
        id: '2',
        name: 'Tailored Women\'s Blazer',
        description: 'Structured blazer crafted for a polished and sophisticated look.',
        price: 179.00,
        compareAtPrice: 249.00,
        image: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=500&h=500&fit=crop',
        ],
        category: 'women',
        subcategory: 'outerwear',
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Black', 'Beige', 'Navy'],
        material: 'Wool Blend',
        careInstructions: 'Dry clean only',
        inStock: true,
        inventory: 28,
        rating: 4.9,
        reviews: 89,
        sku: 'SKU-002',
        createdAt: new Date('2024-01-20'),
    },
    {
        id: '3',
        name: 'Ribbed Cotton T-Shirt',
        description: 'Soft premium cotton tee designed for everyday comfort and effortless styling.',
        price: 39.00,
        compareAtPrice: 59.00,
        image: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=500&h=500&fit=crop',
        ],
        category: 'women',
        subcategory: 'tops',
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['White', 'Black', 'Pink', 'Beige'],
        material: 'Organic Cotton',
        careInstructions: 'Machine wash cold',
        inStock: true,
        inventory: 120,
        rating: 4.7,
        reviews: 256,
        sku: 'SKU-003',
        createdAt: new Date('2024-01-25'),
    },
    {
        id: '4',
        name: 'Cashmere Knit Sweater',
        description: 'Luxuriously soft knit sweater designed for warmth and comfort.',
        price: 139.00,
        compareAtPrice: 199.00,
        image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500&h=500&fit=crop',
        ],
        category: 'women',
        subcategory: 'knitwear',
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Cream', 'Grey', 'Pink'],
        material: 'Cashmere Blend',
        careInstructions: 'Hand wash only',
        inStock: true,
        inventory: 42,
        rating: 4.8,
        reviews: 134,
        sku: 'SKU-007',
        createdAt: new Date('2024-02-15'),
    },
    {
        id: '5',
        name: 'Pleated Midi Skirt',
        description: 'Flowing midi skirt with elegant pleats for versatile styling.',
        price: 119.00,
        image: 'https://images.unsplash.com/photo-1583496661160-fb5886a13d77?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1583496661160-fb5886a13d77?w=500&h=500&fit=crop',
        ],
        category: 'women',
        subcategory: 'skirts',
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Cream', 'Black', 'Dusty Rose'],
        material: 'Polyester Blend',
        careInstructions: 'Gentle wash',
        inStock: true,
        inventory: 34,
        rating: 4.5,
        reviews: 67,
        sku: 'SKU-005',
        createdAt: new Date('2024-02-05'),
    },
    {
        id: '6',
        name: 'Women\'s Leather Handbag',
        description: 'Premium leather handbag featuring a spacious interior and classic design.',
        price: 249.00,
        compareAtPrice: 349.00,
        image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500&h=500&fit=crop',
        ],
        category: 'women',
        subcategory: 'bags',
        colors: ['Tan', 'Black', 'Brown'],
        material: 'Genuine Leather',
        careInstructions: 'Clean with leather conditioner',
        inStock: true,
        inventory: 15,
        rating: 4.9,
        reviews: 92,
        sku: 'SKU-006',
        createdAt: new Date('2024-02-10'),
    },
    {
        id: '7',
        name: 'High-Waisted Denim Jeans',
        description: 'Modern straight-leg jeans with a flattering high-rise fit.',
        price: 99.00,
        compareAtPrice: 149.00,
        image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500&h=500&fit=crop',
        ],
        category: 'women',
        subcategory: 'bottoms',
        sizes: ['24', '25', '26', '27', '28', '29', '30', '31', '32'],
        colors: ['Blue', 'Black', 'Light Wash'],
        material: 'Premium Denim',
        careInstructions: 'Machine wash cold',
        inStock: true,
        inventory: 67,
        rating: 4.6,
        reviews: 178,
        sku: 'SKU-004',
        createdAt: new Date('2024-02-01'),
    },
    {
        id: '8',
        name: "Women's Platform Sneakers",
        description: 'Minimalist platform sneakers designed for everyday wear and comfort.',
        price: 129.00,
        compareAtPrice: 179.00,
        image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&h=500&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&h=500&fit=crop',
        ],
        category: 'women',
        subcategory: 'footwear',
        sizes: ['5', '6', '7', '8', '9', '10'],
        colors: ['White', 'Beige', 'Black'],
        material: 'Leather',
        careInstructions: 'Wipe clean',
        inStock: true,
        inventory: 56,
        rating: 4.7,
        reviews: 145,
        sku: 'SKU-008',
        createdAt: new Date('2024-02-20'),
    }
]